name: loyalty_app
description: Loyalty program app with tiered access to services
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.1
  json_annotation: ^4.9.0
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  # Backend (optional; we will wire later)
  firebase_core: ^2.27.0
  firebase_auth: ^4.18.0
  cloud_firestore: ^4.15.8
  firebase_crashlytics: ^3.5.6
  firebase_analytics: ^10.10.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  generate: true

